export const SET_DRAWER_TABLE = "SET_DRAWER_TABLE";
export const SET_ITEM_MODAL = "SET_ITEM_MODAL";
export const SET_WHISHLIST_MODAL = "SET_WHISHLIST_MODAL";
export const TOGGLE_CREATE_ACCOUNT = "TOGGLE_CREATE_ACCOUNT";
export const GET_PRODUCT_LIST_DATA = "GET_PRODUCT_LIST_DATA";
export const GET_PRODUCT_SALE_LIST_DATA = "GET_PRODUCT_SALE_LIST_DATA";
export const SET_IS_PENDING = "SET_IS_PENDING";
export const ON_LAZY_LOADING = "ON_LAZY_LOADING";
export const OFF_LAZY_LOADING = "OFF_LAZY_LOADING";
export const AMOUNT_KIND_FOOD = "AMOUNT_KIND_FOOD";
export const SET_RANGE_PRICE = "SET_RANGE_PRICE";
export const DEFAULT_SORTING_SEARCH = "DEFAULT_SORTING_SEARCH";
export const PRICE_LOW_HIGH_SEARCH = "PRICE_LOW_HIGH_SEARCH";
export const PRICE_HIGH_LOW_SEARCH = "PRICE_HIGH_LOW_SEARCH";
export const LATEST_SEARCH = "LATEST_SEARCH";
export const LIST_CATEGORY = "LIST_CATEGORY";

