export const SET_DRAWER_TABLE = "SET_DRAWER_TABLE";
export const SET_ITEM_MODAL = "SET_ITEM_MODAL";
export const SET_WHISHLIST_MODAL = "SET_WHISHLIST_MODAL";
export const TOGGLE_CREATE_ACCOUNT = "TOGGLE_CREATE_ACCOUNT";
export const GET_PRODUCT_LIST_DATA = "GET_PRODUCT_LIST_DATA";
